<?php

/**
 * turbosms.ua HTTP API implementation.
 *
 * @author Anton Kalochelitis <developing.w@gmail.com>
 * @version 2.1.0
 */

namespace DevelopingW\TurboSMSua;

class REQUEST_STATUS
{
    const OK = 0;
    const PONG = 1;
    const REQUIRED_TOKEN = 103;
    const REQUIRED_CONTENT = 104;
    const REQUIRED_AUTH = 105;
    const REQUIRED_ACTIVE_USER = 106;
    const REQUIRED_VIBER_SESSION = 107;
    const REQUIRED_MESSAGE_SENDER = 200;
    const REQUIRED_MESSAGE_TEXT = 201;
    const REQUIRED_MESSAGE_RECIPIENT = 202;
    const REQUIRED_BALANCE = 203;
    const REQUIRED_MESSAGE_BUTTON = 204;
    const REQUIRED_MESSAGE_BUTTON_CAPTION = 205;
    const REQUIRED_MESSAGE_BUTTON_ACTION = 206;
    const INVALID_REQUEST = 300;
    const INVALID_TOKEN	= 301;
    const INVALID_MESSAGE_SENDER = 302;
    const INVALID_START_TIME = 303;
    const INVALID_MESSAGE_TEXT = 304;
    const INVALID_PHONE	= 305;
    const INVALID_TTL = 306;
    const INVALID_MESSAGE_ID = 307;
    const INVALID_FILE_ID = 308;
    const INVALID_SENDER_ID	= 309;
    const INVALID_CHAT_ID = 310;
    const INVALID_SESSION_ID = 311;
    const INVALID_PAGE = 312;
    const INVALID_ROWS = 313;
    const NOT_ALLOWED_MESSAGE_SENDER = 400;
    const NOT_ALLOWED_MESSAGE_SENDER_NOT_ACTIVE	= 401;
    const NOT_ALLOWED_MESSAGE_IMAGE	= 402;
    const NOT_ALLOWED_START_TIME = 403;
    const NOT_ALLOWED_NUMBER_STOPLIST = 404;
    const NOT_ALLOWED_RECIPIENTS_LIMIT = 405;
    const NOT_ALLOWED_RECIPIENT_COUNTRY = 406;
    const NOT_ALLOWED_RECIPIENT_DUPLICATE = 407;
    const NOT_ALLOWED_MESSAGE_BUTTON_TEXT_LENGTH = 408;
    const NOT_ALLOWED_MESSAGE_TTL = 409;
    const NOT_ALLOWED_MESSAGE_TRANSACTION_CONTENT = 410;
    const NOT_ALLOWED_MESSAGE_DATA = 411;
    const NOT_ALLOWED_MESSAGE_TEXT = 412;
    const NOT_ALLOWED_MESSAGE_TEXT_LENGTH = 413;
    const NOT_ALLOWED_MESSAGE_ID = 414;
    const NOT_ALLOWED_MESSAGE_TRANSACTION_SENDER = 415;
    const NOT_ALLOWED_MESSAGE_TRANSACTION_PATTERN = 416;
    const NOT_ALLOWED_FILE_ID = 417;
    const NOT_ALLOWED_FILE_EMPTY = 418;
    const NOT_ALLOWED_FILE_TYPE = 419;
    const NOT_ALLOWED_FILE_SIZE = 420;
    const NOT_ALLOWED_MESSAGE_TRAFFIC_TYPE = 421;
    const NOT_ALLOWED_SESSION_OUTBOX_LIMIT = 422;
    const NOT_ALLOWED_FILE_NAME_LENGTH = 423;
    const FAILED_CONVERT_RESULT2JSON = 500;
    const FAILED_CONVERT_RESULT2XML = 501;
    const FAILED_PARSE_BODY	= 502;
    const FAILED_SMS_SEND = 503;
    const FAILED_VIBER_SEND = 504;
    const FAILED_SAVE_IMAGE = 505;
    const FAILED_SAVE_FILE = 506;
    const SUCCESS_MESSAGE_ACCEPTED = 800;
    const SUCCESS_MESSAGE_SENT = 801;
    const SUCCESS_MESSAGE_PARTIAL_ACCEPTED = 802;
    const SUCCESS_MESSAGE_PARTIAL_SENT = 803;
    const FATAL_ERROR = 999;
}